# Generated by Django 2.1.2 on 2018-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
