# Generated by Django 2.1.2 on 2018-10-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20181009_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bachelor_of_Science', models.CharField(max_length=50)),
                ('Institutionu', models.CharField(max_length=50)),
                ('session', models.IntegerField()),
                ('HSC', models.CharField(blank=True, max_length=50)),
                ('Backgroundh', models.CharField(max_length=50)),
                ('Institutionh', models.CharField(max_length=50)),
                ('Boardh', models.CharField(max_length=50)),
                ('resulth', models.IntegerField()),
                ('passingyearh', models.IntegerField()),
                ('SSC', models.CharField(blank=True, max_length=50)),
                ('Backgrounds', models.CharField(max_length=50)),
                ('Institutions', models.CharField(max_length=50)),
                ('Boards', models.CharField(max_length=50)),
                ('results', models.IntegerField()),
                ('passingyears', models.IntegerField()),
            ],
        ),
    ]
