# Generated by Django 2.1.2 on 2018-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='edu', max_length=50),
            preserve_default=False,
        ),
    ]
