# Generated by Django 2.1.2 on 2018-10-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_education_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('expert', models.CharField(max_length=50)),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('python', models.CharField(max_length=50)),
                ('android', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=50)),
                ('html', models.CharField(max_length=50)),
            ],
        ),
    ]
