# Generated by Django 2.1.2 on 2018-10-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_language_programming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='expert',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
