# Generated by Django 2.1.2 on 2018-10-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
