# Generated by Django 2.1.2 on 2018-10-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
