# Generated by Django 2.1.2 on 2018-10-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('proone', models.CharField(max_length=100)),
                ('protwo', models.CharField(max_length=100)),
                ('prothree', models.CharField(max_length=100)),
                ('profour', models.CharField(max_length=100)),
                ('profive', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
